#!/usr/bin/env bash
#
# `a` with no arguments opens the current directory in Atom Editor, otherwise
# opens the given location

a () {
    if [ $# -eq 0 ]; then
        atom .;
    else
        atom "$@";
    fi;
}
