#!/usr/bin/env bash
#
# Homebrew Cask Upgrades
# Supports iterative/optional upgrading of all installed casks.

cask_upgrade () {
  if [[ "$1" != '--continue' ]]; then
    echo "Removing brew cache"
    rm -rf "$(brew --cache)"
    echo "Running brew update"
    brew update
  fi
  for cask_name in $(brew cask list); do
    echo -e "\n\nInstalled versions of $cask_name: "
    ls "/opt/homebrew-cask/Caskroom/$cask_name"
    echo "Cask info for $cask_name"
    brew cask info "$cask_name"
    select ynx in "Yes" "No" "Exit"; do
      case $ynx in
        [yY] | [yY][Ee][Ss] )
          echo "Uninstalling $cask_name"
          brew cask uninstall --force "$cask_name"
          echo "Re-installing $cask_name"
          brew cask install "$cask_name"
          break;;
        [nN] | [n|N][O|o] )
          echo "Skipping $cask_name"
          break;;
        * )
          echo "Exiting brew-cask-upgrade"
          return;;
      esac
    done
  done
}
