#!/usr/bin/env bash
#
# Homebrew Cask Install
# Supports install and reinstalling casks.

cask_install () {
  if ! type "brew" &> /dev/null; then
    echo "'brew' command not found."
    return 1
  fi
  local caskroom_path=""
  [[ -d "/opt/homebrew-cask/Caskroom" ]] && caskroom_path="/opt/homebrew-cask/Caskroom"
  [[ -d "$(brew --prefix)/Caskroom" ]] && caskroom_path="$(brew --prefix)/Caskroom"
  if [[ -z "$caskroom_path" ]]; then
    echo "Caskroom path not found."
    return 1
  fi
  if [[ "${1:-}" ]]; then
    echo "Removing brew cache"
    rm -rf "$(brew --cache)"
    echo "Running brew update"
    brew update
    if [[ -d "$caskroom_path/$1" ]]; then
      echo "Uninstalling '$1'"
      brew uninstall --force --cask "$1"
      echo "Re-installing '$1'"
    else
      echo "Installing '$1'"
    fi
    brew install --cask "$1"
  else
    echo "No cask provided: '${1:-}'"
  fi
}
