#!/usr/bin/env bash
#
# Get a character’s Unicode code point

codepoint() {
  perl -e "use utf8; print sprintf('U+%04X', ord(\"$*\"))"
  # print a newline unless we’re piping the output to another program
  [[ -t 1 ]] && echo ""
}
