#!/usr/bin/env bash
#
# Create a data URL from a file

dataurl() {
  local mimeType
  mimeType=$(file -b --mime-type "$1")
  [[ $mimeType == text/* ]] && mimeType="${mimeType};charset=utf-8"
  echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')"
}
