#!/usr/bin/env bash
#
# UTF-8-encode a string of Unicode symbols

escape() {
  printf "\\\x%s" "$(printf "%s" "$*" | xxd -p -c1 -u)"
  # print a newline unless we’re piping the output to another program
  [[ -t 1 ]] && echo ""
}
