#!/usr/bin/env bash
#
# Usage: extract <file>
# Description: extracts archived files / mounts disk images
# Note: .dmg/hdiutil is Mac macOS-specific.
# credit: http://nparikh.org/notes/zshrc.txt
# shellcheck disable=SC2002

extract() {
  local _in
  _in="${1:-}"
  if [ -f "$_in" ]; then
    case "$_in" in
    *.tar.bz2) tar -jxvf "$_in" ;;
    *.tar.gz) tar -zxvf "$_in" ;;
    *.bz2) bunzip2 "$_in" ;;
    *.dmg) hdiutil mount "$_in" ;;
    *.gz) gunzip "$_in" ;;
    *.tar) tar -xvf "$_in" ;;
    *.tbz2) tar -jxvf "$_in" ;;
    *.tgz) tar -zxvf "$_in" ;;
    *.zip) unzip "$_in" ;;
    *.ZIP) unzip "$_in" ;;
    *.pax) cat "$_in" | pax -r ;;
    *.pax.Z) uncompress "$_in" --stdout | pax -r ;;
    *.rar) unrar x "$_in" ;;
    *.Z) uncompress "$_in" ;;
    *) echo "'$_in' cannot be extracted/mounted via extract()" ;;
    esac
  else
    echo "'$_in' is not a valid file"
  fi
}
