#!/usr/bin/env bash
#
# Determine size of a file or total size of a directory

fs() {
  local arg
  arg=-sh
  du -b /dev/null >/dev/null 2>&1 && arg=-sbh
  if [[ -n "$*" ]]; then
    du $arg -- "$@"
  else
    du $arg -- .[^.]* *
  fi
}
