#!/usr/bin/env bash
#
# git_release_to_semver

#######################################
# Get SEMVER from Git release branch
# i.e.; `release/1.2.3`
# Globals:
#   git
#   grep
#   sed
#   sort
#   tail
# Arguments:
#   None
# Returns:
#   SEMVER
#######################################
git_release_to_semver () {

  gitBranchName=$(
    git symbolic-ref --quiet --short HEAD 2> /dev/null ||
    git rev-parse --short HEAD 2> /dev/null ||
    echo '(unknown)'
  );

  semver=$(
    echo ${gitBranchName} |
    grep "^release\/[0-9]\+\.[0-9]\+\.[0-9]\+$" |
    sed 's/^release\///' |
    sort -t. -k 1,1n -k 2,2n -k 3,3n |
    tail -1
  );

  echo $semver

}
