#!/usr/bin/env bash
#
# symlink file
# example; link_file this.file ../that.file

link_file() {
  local src="${1:-}" dst="${1:-}"
  local overwrite backup skip action

  if [[ -f "$dst" ]] || [[ -d "$dst" ]] || [[ -L "$dst" ]]; then

    if [[ "$overwrite_all" == "false" ]] && [[ "$backup_all" == "false" ]] && [[ "$skip_all" == "false" ]]; then

      if cmp -s "$dst" "$src"; then
        skip=true
      else
        printf "\033[2K\r\n [\033[0;33m ?? \033[0m]  File already exists: %s ($(basename %s)), what do you want to do?\n\
                [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all? \n" "$dst" "$src"
        read -r -n 1 action

        case "$action" in
        o)
          overwrite=true
          ;;
        O)
          overwrite_all=true
          ;;
        b)
          backup=true
          ;;
        B)
          backup_all=true
          ;;
        s)
          skip=true
          ;;
        S)
          skip_all=true
          ;;
        *) ;;
        esac
      fi
    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [[ "$overwrite" == "true" ]]; then
      rm -rf "$dst"
      printf "\033[2K\r\n [\033[0;32m OK \033[0m] \033[0;32m Removed %s \033[0m \n" "$dst"
    fi

    if [[ "$backup" == "true" ]]; then
      mv "$dst" "${dst}.backup"
      printf "\033[2K\r\n [\033[0;32m OK \033[0m] \033[0;32m Moved %s to %s.backup \033[0m \n" "$dst" "$dst"
    fi

    if [[ "$skip" == "true" ]]; then
      printf "\033[2K\r\n [\033[0;32m OK \033[0m] \033[0;32m Skipped %s \033[0m \n" "$src"
    fi
  fi

  # "false" or empty
  if [[ "$skip" != "true" ]]; then
    ln -s "$1" "$2"
    printf "\033[2K\r\n [\033[0;32m OK \033[0m] \033[0;32m Linked %s to %s \033[0m \n" "$1" "$2"
  fi
}
