#!/usr/bin/env bash
#
# rsyncIt: Sync directories to/from a mounted volume
# Usage:
#   rsyncit up "${HOME}/Documents/" "/Volumes/DriveName/Documents"
#   rsyncit down "/Volumes/DriveName/Documents/" "${HOME}/Documents"

rsyncit() {
  local FLAGS=()
  if [[ "${1:-}" != "up" ]] && [[ "${1:-}" != "down" ]]; then
    echo "ERROR: Specify 'up' or 'down' as the first argument."
    return 1
  else
    if [[ "$1" = "up" ]]; then
      FLAGS+=(--delete-after)
      FLAGS+=(--delete-excluded)
    fi
  fi
  if [[ -z "${2:-}" ]]; then
    echo "ERROR: Specify a source path as the second argument."
    return 1
  fi
  if [[ -z "${3:-}" ]]; then
    echo "ERROR: Specify a destination path as the third or last argument."
    return 1
  fi

  FLAGS+=(--exclude "._*")
  FLAGS+=(--exclude ".cache")
  FLAGS+=(--exclude ".com.apple.timemachine.donotpresent")
  FLAGS+=(--exclude ".disk_label*")
  FLAGS+=(--exclude ".DocumentRevisions-V100")
  FLAGS+=(--exclude ".DS_Store")
  FLAGS+=(--exclude ".fseventsd")
  FLAGS+=(--exclude ".grunt")
  FLAGS+=(--exclude ".lock-wscript")
  FLAGS+=(--exclude ".sass-cache")
  FLAGS+=(--exclude ".Spotlight-V100")
  FLAGS+=(--exclude ".TemporaryItems")
  FLAGS+=(--exclude ".Trashes")
  FLAGS+=(--exclude ".VolumeIcon.icns")
  FLAGS+=(--exclude "*.log")
  FLAGS+=(--exclude "bower_components/")
  FLAGS+=(--exclude "connect.lock")
  FLAGS+=(--exclude "coverage/")
  FLAGS+=(--exclude "dist/")
  FLAGS+=(--exclude "ehthumbs.db")
  FLAGS+=(--exclude "Icon?")
  FLAGS+=(--exclude "logs/")
  FLAGS+=(--exclude ".sonarlint/")
  FLAGS+=(--exclude ".nyc_output/")
  FLAGS+=(--exclude "node_modules/")
  FLAGS+=(--exclude "out-tsc/")
  FLAGS+=(--exclude "temp/")
  FLAGS+=(--exclude "Thumbs.db")
  FLAGS+=(--exclude "tmp/")
  FLAGS+=(--exclude "vendor/")
  FLAGS+=(--exclude "yarn-error.log")

  echo "Syncing..."
  echo "  ${2:-}"
  if [[ -n "${8:-}" ]]; then
    echo "  ${3:-}"
    echo "  ${4:-}"
    echo "  ${5:-}"
    echo "  ${6:-}"
    echo "  ${7:-}"
    echo "To..."
    echo "  ${8:-}"
    if [[ ! -e "${8:-}" ]]; then
      if [[ -d "$7" ]]; then
        echo "Creating directory: ${8:-}"
        mkdir -p "${8:-}"
      elif [[ -f "$7" ]]; then
        echo "Creating directory: $(dirname "${8:-}")"
        mkdir -p "$(dirname "${8:-}")"
      fi
    fi
    rsync -au --progress --stats "${FLAGS[@]}" "$2" "$3" "${4:-}" "${5:-}" "${6:-}" "${7:-}" "${8:-}"
  elif [[ -n "${7:-}" ]]; then
    echo "  ${3:-}"
    echo "  ${4:-}"
    echo "  ${5:-}"
    echo "  ${6:-}"
    echo "To..."
    echo "  ${7:-}"
    if [[ ! -e "${7:-}" ]]; then
      if [[ -d "$6" ]]; then
        echo "Creating directory: ${7:-}"
        mkdir -p "${7:-}"
      elif [[ -f "$6" ]]; then
        echo "Creating directory: $(dirname "${7:-}")"
        mkdir -p "$(dirname "${7:-}")"
      fi
    fi
    rsync -au --progress --stats "${FLAGS[@]}" "$2" "$3" "${4:-}" "${5:-}" "${6:-}" "${7:-}"
  elif [[ -n "${6:-}" ]]; then
    echo "  ${3:-}"
    echo "  ${4:-}"
    echo "  ${5:-}"
    echo "To..."
    echo "  ${6:-}"
    if [[ ! -e "${6:-}" ]]; then
      if [[ -d "$5" ]]; then
        echo "Creating directory: ${6:-}"
        mkdir -p "${6:-}"
      elif [[ -f "$5" ]]; then
        echo "Creating directory: $(dirname "${6:-}")"
        mkdir -p "$(dirname "${6:-}")"
      fi
    fi
    rsync -au --progress --stats "${FLAGS[@]}" "$2" "$3" "${4:-}" "${5:-}" "${6:-}"
  elif [[ -n "${5:-}" ]]; then
    echo "  ${3:-}"
    echo "  ${4:-}"
    echo "To..."
    echo "  ${5:-}"
    if [[ ! -e "${5:-}" ]]; then
      if [[ -d "$4" ]]; then
        echo "Creating directory: ${5:-}"
        mkdir -p "${5:-}"
      elif [[ -f "$4" ]]; then
        echo "Creating directory: $(dirname "${5:-}")"
        mkdir -p "$(dirname "${5:-}")"
      fi
    fi
    rsync -au --progress --stats "${FLAGS[@]}" "$2" "$3" "${4:-}" "${5:-}"
  elif [[ -n "${4:-}" ]]; then
    echo "  ${3:-}"
    echo "To..."
    echo "  ${4:-}"
    if [[ ! -e "${4:-}" ]]; then
      if [[ -d "$3" ]]; then
        echo "Creating directory: ${4:-}"
        mkdir -p "${4:-}"
      elif [[ -f "$3" ]]; then
        echo "Creating directory: $(dirname "${4:-}")"
        mkdir -p "$(dirname "${4:-}")"
      fi
    fi
    rsync -au --progress --stats "${FLAGS[@]}" "$2" "$3" "${4:-}"
  else
    echo "To..."
    echo "  ${3:-}"
    if [[ ! -e "${3:-}" ]]; then
      if [[ -d "$2" ]]; then
        echo "Creating directory: ${3:-}"
        mkdir -p "${3:-}"
      elif [[ -f "$2" ]]; then
        echo "Creating directory: $(dirname "${3:-}")"
        mkdir -p "$(dirname "${3:-}")"
      fi
    fi
    rsync -au --progress --stats "${FLAGS[@]}" "$2" "$3"
  fi
}
