#!/usr/bin/env bash
#
# `s` with no arguments opens the current directory in Sublime Text, otherwise
# opens the given location

s () {
    if [ $# -eq 0 ]; then
        subl .;
    else
        subl "$@";
    fi;
}
