#!/usr/bin/env bash
#
# Shell Response Helper: ERROR

sh_error () {
    # shellcheck disable=SC2059
    printf "${ClearNewLine:-} [${Red:-} ER ${Reset:-}]  ${Red:-}${1:-}${Reset:-} \\n"
}

# shellcheck disable=SC2034
[[ -z "${ZSH_NAME:-}" ]] && typeset -fx sh_error
