#!/usr/bin/env bash
#
# Shell Response Helper: FAIL

sh_fail () {
    # shellcheck disable=SC2059
    printf "${ClearNewLine:-} [${Red:-}FAIL${Reset:-}]  ${Red:-}${1:-}${Reset:-} \\n"
    echo ''
    exit 2
}

# shellcheck disable=SC2034
[[ -z "${ZSH_NAME:-}" ]] && typeset -fx sh_fail
