#!/usr/bin/env bash
#
# Shell Response Helper: HEADING

sh_heading() {
  # shellcheck disable=SC2059
  printf "${ClearNewLine:-}\\n\\n${Bold:-}${IMagenta:-}❯❯❯❯❯❯❯❯${Reset:-} ${Bold:-}${ICyan:-}${Underline:-}${1:-}${Reset:-} ${Bold:-}${IMagenta:-}❯${IYellow:-}❯${IGreen:-}❯${Reset:-}\\n\\n"
}
