#!/usr/bin/env bash
#
# Shell Response Helper: INFO

sh_info () {
    # shellcheck disable=SC2059
    printf "${ClearNewLine:-} [${Blue:-} .. ${Reset:-}]  ${1:-} \\n"
}

# shellcheck disable=SC2034
[[ -z "${ZSH_NAME:-}" ]] && typeset -fx sh_info
