#!/usr/bin/env bash
#
# Decode \x{ABCD}-style Unicode escape sequences

unidecode() {
  perl -e "binmode(STDOUT, ':utf8'); print \"$*\""
  # print a newline unless we're piping the output to another program
  [[ -t 1 ]] && echo ""
}
