---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

# Activates formatting and auto-fixing
APPLY_FIXES: none
# https://megalinter.io/latest/supported-linters/
# If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
ENABLE:
  - BASH
  # - CLOUDFORMATION
  # - CSS
  - DOCKERFILE
  - ENV
  # - GHERKIN
  # - HTML
  - JAVASCRIPT
  - JSON
  # - KUBERNETES
  - MARKDOWN
  # - OPENAPI
  - REPOSITORY
  # - TERRAFORM
  # - XML
  - YAML
DISABLE_LINTERS:
  - JAVASCRIPT_PRETTIER
  - JAVASCRIPT_STANDARD
  - JSON_PRETTIER
  - KUBERNETES_KUBEVAL
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_REMARK_LINT
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_GOODCHECK
  - REPOSITORY_SEMGREP
  - REPOSITORY_SYFT
  - REPOSITORY_TRIVY
  - TERRAFORM_CHECKOV
  - TERRAFORM_KICS
  - TERRAFORM_TERRASCAN
BASH_SHELLCHECK_FILE_EXTENSIONS: ['', '.sh', '.bash', '.dash', '.ksh', '.zsh']
BASH_SHELLCHECK_FILTER_REGEX_INCLUDE: '(bin/*|scripts/*)'
EXCLUDED_DIRECTORIES: ['.terraform', 'node_modules']
FLAVOR_SUGGESTIONS: false
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.devcontainer/|\.vscode/)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
PRINT_ALL_FILES: false
PRINT_ALPACA: false
REPORTERS_MARKDOWN_TYPE: simple
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: false
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(\.github/workflows)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(\.github/workflows)'
